window.WAICE_SITE_CONTENT = {
  settings: {
    siteName: "WaiceChe.com",
    primaryLanguage: "en",
    supportedLanguages: ["en", "zhHant", "zhHans"],
    musicFunUrl: "https://musicfun100.com",
    contactEmail: "hello@waiceche.com",
    youtubeIntroUrl: "",
    youtubePosterNote: "Replace this placeholder with Waice's YouTube founder introduction video thumbnail.",
  },
  images: {
    seatedFounderPortrait: {
      src: "./assets/portraits/waice-seated-founder-portrait.png",
      alt: "Waice Che seated founder portrait",
      caption: "Waice Che, Founder of Music Fun 100",
      ratio: "4:5",
      focalPoint: "face center",
      status: "public",
    },
    mozartConcertMacauCulturalCentre: {
      src: "./assets/music/concert-night-of-mozart-macau-cultural-centre.jpg",
      alt: "Waice Che performing flute with piano accompaniment at Macau Cultural Centre",
      caption: "Concert of the Night of Mozart at Macau Cultural Centre",
      ratio: "16:9",
      focalPoint: "stage center",
      status: "public",
    },
    paulEdmundDaviesMasterClass: {
      src: "./assets/music/master-class-paul-edmund-davies.jpg",
      alt: "Waice Che with flutist Paul Edmund-Davies after a master class",
      caption: "Master Class of Paul Edmund-Davies",
      ratio: "4:5",
      focalPoint: "faces center",
      status: "public",
    },
    trevorWyeMasterClass: {
      src: "./assets/music/master-class-trevor-wye.jpg",
      alt: "Waice Che with flutist Trevor Wye after a master class",
      caption: "Master Class of Trevor Wye",
      ratio: "4:5",
      focalPoint: "faces center",
      status: "public",
    },
    teachingPhilosophyStudents: {
      src: "./assets/music/teaching-philosophy-students.jpg",
      alt: "Waice Che smiling with young flute students",
      caption: "Teaching Philosophy",
      ratio: "16:9",
      focalPoint: "faces center",
      status: "public",
    },
  },
  navigation: [
    { id: "home", label: "Home", status: "public" },
    { id: "about", label: "About", status: "public" },
    { id: "music", label: "Music & Education", status: "public" },
    { id: "students", label: "Student Success", status: "public" },
    { id: "leadership", label: "Leadership & Entrepreneurship", status: "public" },
    { id: "media", label: "Media & Press", status: "public" },
    { id: "founder", label: "Founder / Music Fun 100", status: "public" },
    { id: "contact", label: "Contact", status: "public" },
  ],
  pages: {
    home: {
      id: "home",
      status: "public",
      seo: {
        title: "Waice Che | Musician, Educator, Entrepreneur",
        description: "Founder personal brand website for Waice Che, Founder of Music Fun 100.",
      },
      hero: {
        title: "Waice Che",
        subtitle: "Musician · Educator · Entrepreneur",
        founderLine: "Founder of Music Fun 100",
        body: "With 24 years of music education experience, a cross-cultural teaching background and an entrepreneurial perspective, Waice Che founded Music Fun 100 to make trusted, international music education more accessible to teachers, students and parents.",
        belief: "Every teacher deserves to be seen. Every student deserves a wider world through music.",
        videoTitle: "Founder Introduction Video",
        videoCaption: "A personal introduction from Waice about music education, online teaching, business experience and the vision behind Music Fun 100.",
      },
      highlights: [
        { value: "24 Years", label: "Music education experience", status: "public" },
        { value: "Global Students", label: "Students from Canada, United States, Australia, New Zealand, Thailand, Singapore, Italy, UK, Japan, China, Hong Kong, Macau, and more.", status: "public" },
        { value: "Founder Vision", label: "Making music education more accessible", status: "public" },
      ],
      sections: [
        {
          type: "statement",
          title: "A New Path for Music Education",
          body: "Waice believes online education can succeed when it is built with trust, strong communication and meaningful teaching. Through Music Fun 100, she hopes to help teachers find more active student opportunities and help students receive wider international knowledge.",
          status: "public",
        },
        {
          type: "proof-grid",
          title: "A Founder Story Built From Experience",
          items: [
            "Flute and harp music training with accurate institutional wording.",
            "Personal youth music competition achievements from Macau.",
            "Students from different regions achieving strong results through online learning.",
            "Business, public image and international exchange experience.",
          ],
          status: "public",
        },
      ],
    },
    about: {
      id: "about",
      status: "public",
      title: "About Waice",
      intro: "Waice Che is a Macau-born musician, educator and entrepreneur whose work connects music training, teaching, public leadership and international perspective.",
      sections: [
        {
          title: "From Music Training to Teaching",
          body: "Waice's professional story begins with music training in Macau, including flute and harp studies. Her education background should be described using the exact official school and course wording from her certificate, without overstating degree level or institutional status.",
          imageRole: "Macau music training / certificate / flute portrait",
          status: "public",
        },
        {
          title: "What Music Has Given Me",
          body: "Music gave Waice mentors, discipline and a way to connect with people across cultures. Through teaching, she has been able to share knowledge with students from different countries and help them build confidence, happiness and friendships through music.",
          imageRole: "Warm teaching or music portrait",
          status: "public",
        },
        {
          title: "Founder Journey",
          body: "Her journey as an educator and entrepreneur led naturally to Music Fun 100: a platform created from real teaching experience, respect for musicians, and a belief that every student deserves access to a broader musical world.",
          imageRole: "Founder portrait / international setting",
          imageKey: "seatedFounderPortrait",
          status: "public",
        },
      ],
    },
    music: {
      id: "music",
      status: "public",
      title: "Music & Education",
      intro: "Flute and Harp Education by Macau Music Conservatory",
      sections: [
        {
          title: "Flute & Harp Studies",
          body: "Use official certificate wording for the Macau performing arts institution and course name. The language should be accurate, respectful and non-inflated.",
          status: "public",
        },
        {
          title: "Personal Macau Youth Music Achievements",
          body: "Personal music competition achievements from Waice's youth can be listed here once names, years and award titles are confirmed.",
          status: "public",
        },
        {
          title: "24 Years in Music Education",
          body: "Waice's long-term work as a music educator is one of the central foundations of the founder story. This section should explain her teaching philosophy, method and the meaning of music in student growth.",
          status: "public",
        },
        {
          title: "Teaching Philosophy",
          body: "Music education is not only about lessons. It is about helping students express emotion, build discipline, develop confidence, make friends and carry music into their lives with joy.",
          imageKey: "teachingPhilosophyStudents",
          status: "public",
        },
        {
          title: "Music Promotion & Adjudication",
          body: "Waice previously served as Vice President of the Macau Youth Music Promotion Association and as an adjudicator for selected Macau music competitions. Exact official names and event details can be refined when source material is supplied.",
          status: "public",
        },
      ],
      gallery: {
        title: "Music Performance Photos",
        intro: "Selected performance and master class moments from Waice's music journey.",
        items: [
          "mozartConcertMacauCulturalCentre",
          "paulEdmundDaviesMasterClass",
          "trevorWyeMasterClass",
        ],
      },
    },
    students: {
      id: "students",
      status: "public",
      title: "Student Success",
      intro: "Student achievements are presented separately from Waice's personal awards, keeping the portfolio clear, credible and respectful.",
      sections: [
        {
          title: "Competition Highlights",
          body: "Add selected student competition results here. Keep the list concise and source-backed where possible.",
          status: "public",
        },
        {
          title: "Student Stories",
          body: "Share short stories of students who gained confidence, musical growth, international exposure or meaningful opportunities through learning.",
          status: "public",
        },
        {
          title: "Global Online Learning Results",
          body: "During four years of online teaching, Waice's students from different parts of the world achieved strong results, supporting her belief that online music education can be effective and meaningful.",
          status: "public",
        },
      ],
    },
    leadership: {
      id: "leadership",
      status: "public",
      title: "Leadership & Entrepreneurship",
      intro: "This page presents Waice's business, public image and civic leadership experience as supporting evidence for her founder journey.",
      groups: [
        {
          title: "Public Image & Modeling",
          items: [
            "Senior Macau model",
            "Award-winning model / Third Place, Macau Modeling Competition",
          ],
          status: "public",
        },
        {
          title: "Entrepreneurial Experience",
          items: [
            "Founder, Glamour Model Agency",
            "Business and environmental technology background",
            "Major environmental forum roadshows",
          ],
          status: "public",
        },
        {
          title: "Civic & International Exchange",
          items: [
            "Vice Chairman of 1st Miss Universe Macau Region Contest, pending exact source wording",
            "Executive Committee Member, Social Affairs Department, Macau Youth Elites Association (2nd Term)",
            "Former Vice President, Macau Youth Music Promotion Association",
            "Meituan and Ximalaya delegation / industry exchange visits",
          ],
          status: "public",
        },
      ],
    },
    media: {
      id: "media",
      status: "public",
      title: "Media & Press",
      intro: "A curated source-led page for interviews, press features, guest lectures and public appearances.",
      mediaItems: [
        {
          title: "City University Guest Lecturer",
          source: "Official school source/link to be added",
          type: "Guest lecture",
          status: "needs-source",
        },
        {
          title: "Portuguese Magazine Interview",
          source: "Source supplied / link or scan to be added",
          type: "Interview",
          status: "public",
        },
        {
          title: "Costa Rica University Interview",
          source: "Source to be added",
          type: "Interview",
          status: "needs-source",
        },
      ],
    },
    founder: {
      id: "founder",
      status: "public",
      title: "Founder / Music Fun 100",
      intro: "Music Fun 100 was created from Waice's belief that music has no borders, and that music education should not be limited by geography.",
      letter: [
        "Dear teachers, students and parents,",
        "Music has shaped my life in many meaningful ways.",
        "Through music, I met teachers who guided me, inspired me and helped me understand not only how to perform, but how to grow as a person. Through teaching, I have been able to share what I learned with students from different places, and to see music become part of their confidence, happiness and friendships.",
        "For more than 24 years, I have seen how music can change a student's life. It can help a child express emotions, build discipline, make new friends, and discover a stronger sense of self.",
        "I also understand the reality faced by many music teachers. Not every musician has the time, resources or confidence to build a social media platform, promote their work, communicate with parents and create a stable teaching career on their own.",
        "This is one of the reasons I founded Music Fun 100.",
        "My hope is to build a platform where music teachers are supported, students can find inspiring learning opportunities, and parents can communicate with teachers through respect, clarity and trust.",
        "Looking ahead, I hope Music Fun 100 can help students access more international music information and opportunities, including competitions, festivals, exchanges and learning experiences that broaden their musical vision.",
        "At the heart of this vision is a simple belief: music has no borders. I hope Music Fun 100 can help music education move beyond geographical limits, connecting teachers, students and parents with higher standards of learning, broader cultural understanding and a truly global musical community.",
        "To me, music education is not only about lessons. It is about helping people connect, grow, and carry music into their lives with confidence, joy and a wider view of the world.",
        "With gratitude,",
        "Waice Che",
      ],
      ctas: [
        { label: "Join as a Teacher", url: "https://musicfun100.com" },
        { label: "Find a Music Teacher", url: "https://musicfun100.com" },
      ],
    },
    contact: {
      id: "contact",
      status: "public",
      title: "Contact Waice",
      intro: "For investment partnership, Music Fun 100 collaboration, teacher opportunities, or student and parent inquiries.",
      topics: [
        "Investment partnership",
        "Music Fun 100 partnership",
        "Teacher joining Music Fun 100",
        "Student / parent inquiry",
      ],
    },
    investor: {
      id: "investor",
      status: "hidden",
      title: "Investor Overview",
      intro: "A concise private-facing overview of Waice's founder-market fit and Music Fun 100's long-term education opportunity.",
      points: [
        "24 years of music education experience.",
        "Online teaching experience with students across regions.",
        "Cross-cultural and entrepreneurial background.",
        "A clear understanding of music teachers' career limitations and student acquisition challenges.",
        "A trust-led platform vision for teachers, students and parents.",
        "A long-term international direction: competitions, festivals, exchanges and global music learning opportunities.",
      ],
    },
  },
  adminModel: {
    contentStatuses: ["draft", "needs-source", "ready-to-publish", "public", "archived"],
    imageRatios: ["1:1", "4:5", "16:9", "3:2", "custom"],
    imageFields: [
      "file",
      "altText",
      "caption",
      "subtitle",
      "source",
      "privacy",
      "ratio",
      "focalPoint",
      "customWidth",
      "customHeight",
      "status",
    ],
    futureAdminRoles: ["Waice", "Assistant"],
  },
  translations: {
    zhHant: {
      "Home": "首頁",
      "About": "關於",
      "Music & Education": "音樂與教育",
      "Student Success": "學生成就",
      "Leadership & Entrepreneurship": "領導與創業",
      "Media & Press": "媒體與採訪",
      "Founder / Music Fun 100": "創辦人 / Music Fun 100",
      "Contact": "聯絡",
      "Founder Portfolio": "創辦人作品集",
      "Musician · Educator · Entrepreneur · Founder of Music Fun 100": "音樂人 · 教育者 · 創業者 · Music Fun 100 創辦人",
      "Visit Music Fun 100": "前往 Music Fun 100",
      "Join as a Teacher": "老師加入",
      "Find a Music Teacher": "尋找音樂老師",
      "Founder of Music Fun 100": "Music Fun 100 創辦人",
      "Musician · Educator · Entrepreneur": "音樂人 · 教育者 · 創業者",
      "With 24 years of music education experience, a cross-cultural teaching background and an entrepreneurial perspective, Waice Che founded Music Fun 100 to make trusted, international music education more accessible to teachers, students and parents.": "Waice Che 擁有 24 年音樂教育經驗、跨文化教學背景及創業視野。她創立 Music Fun 100，希望讓值得信任、具國際視野的音樂教育，更容易連接老師、學生與家長。",
      "Every teacher deserves to be seen. Every student deserves a wider world through music.": "每一位老師都值得被看見，每一位學生都值得透過音樂看見更大的世界。",
      "Founder Introduction Video": "創辦人介紹影片",
      "Replace this placeholder with Waice's YouTube founder introduction video thumbnail.": "之後可替換成 Waice 的 YouTube 創辦人介紹影片封面。",
      "A personal introduction from Waice about music education, online teaching, business experience and the vision behind Music Fun 100.": "Waice 親自介紹她的音樂教育、線上教學、商業背景，以及 Music Fun 100 背後的願景。",
      "24 Years": "24 年",
      "Music education experience": "音樂教育經驗",
      "Global Students": "全球學生",
      "Online teaching across regions": "跨地區線上教學",
      "Students from Canada, United States, Australia, New Zealand, Thailand, Singapore, Italy, UK, Japan, China, Hong Kong, Macau, and more.": "學生來自加拿大、美國、澳洲、新西蘭、泰國、新加坡、意大利、英國、日本、中國、香港、澳門等地",
      "Founder Vision": "創辦人願景",
      "Making music education more accessible": "讓音樂教育更容易接觸",
      "A New Path for Music Education": "音樂教育的新方向",
      "Waice believes online education can succeed when it is built with trust, strong communication and meaningful teaching. Through Music Fun 100, she hopes to help teachers find more active student opportunities and help students receive wider international knowledge.": "Waice 相信，只要建立在信任、良好溝通和有意義的教學之上，線上音樂教育是可以成功的。透過 Music Fun 100，她希望幫助老師更主動找到學生資源，也讓學生接觸更廣闊的國際音樂知識。",
      "A Founder Story Built From Experience": "由真實經驗累積而成的創辦人故事",
      "Flute and harp music training with accurate institutional wording.": "以準確、不誇大的方式呈現長笛與豎琴音樂訓練。",
      "Personal youth music competition achievements from Macau.": "Waice 在澳門青年音樂比賽中的個人成就。",
      "Students from different regions achieving strong results through online learning.": "不同地區學生在線上學習中取得良好成績。",
      "Business, public image and international exchange experience.": "商業、公眾形象及國際交流經驗。",
      "About Waice": "關於 Waice",
      "Waice Che is a Macau-born musician, educator and entrepreneur whose work connects music training, teaching, public leadership and international perspective.": "Waice Che 是來自澳門的音樂人、教育者與創業者，她的工作連接音樂訓練、教學、公眾領導力與國際視野。",
      "From Music Training to Teaching": "從音樂訓練到教學",
      "What Music Has Given Me": "音樂帶給我的意義",
      "Founder Journey": "創辦人旅程",
      "Flute and Harp Education by Macau Music Conservatory": "澳門音樂學院長笛與豎琴教育",
      "Flute & Harp Studies": "長笛與豎琴學習",
      "Personal Macau Youth Music Achievements": "澳門青年音樂個人成就",
      "24 Years in Music Education": "24 年音樂教育",
      "Teaching Philosophy": "教學理念",
      "Music Promotion & Adjudication": "音樂推廣與比賽評審",
      "Music Performance Photos": "音樂演出相片",
      "Selected performance and master class moments from Waice's music journey.": "Waice 音樂旅程中的演出與大師班精選時刻。",
      "Concert of the Night of Mozart at Macau Cultural Centre": "澳門文化中心《莫扎特之夜》音樂會",
      "Master Class of Paul Edmund-Davies": "Paul Edmund-Davies 大師班",
      "Master Class of Trevor Wye": "Trevor Wye 大師班",
      "Waice previously served as Vice President of the Macau Youth Music Promotion Association and as an adjudicator for selected Macau music competitions. Exact official names and event details can be refined when source material is supplied.": "Waice 曾擔任澳門青年音樂推廣協會副會長，並曾為部分澳門音樂比賽擔任評委。正式英文名稱及活動資料可在來源提供後再精準修訂。",
      "Student achievements are presented separately from Waice's personal awards, keeping the portfolio clear, credible and respectful.": "學生成就會與 Waice 的個人獎項分開呈現，讓網站更清晰、可信，也更尊重學生。",
      "Leadership & Entrepreneurship": "領導與創業",
      "This page presents Waice's business, public image and civic leadership experience as supporting evidence for her founder journey.": "此頁展示 Waice 的商業、公眾形象及社會領導經驗，作為她創辦人故事的支持證據。",
      "Public Image & Modeling": "公眾形象與模特經歷",
      "Entrepreneurial Experience": "創業經驗",
      "Civic & International Exchange": "社會事務與國際交流",
      "Former Vice President, Macau Youth Music Promotion Association": "澳門青年音樂推廣協會前副會長",
      "Media & Press": "媒體與採訪",
      "A curated source-led page for interviews, press features, guest lectures and public appearances.": "精選訪問、媒體報導、客席講座及公開活動紀錄。",
      "Music Fun 100 was created from Waice's belief that music has no borders, and that music education should not be limited by geography.": "Music Fun 100 源自 Waice 的信念：音樂沒有邊界，音樂教育也不應受地域限制。",
      "Dear teachers, students and parents,": "親愛的老師、學生和家長：",
      "Music has shaped my life in many meaningful ways.": "音樂以很多重要的方式塑造了我的人生。",
      "Through music, I met teachers who guided me, inspired me and helped me understand not only how to perform, but how to grow as a person. Through teaching, I have been able to share what I learned with students from different places, and to see music become part of their confidence, happiness and friendships.": "透過音樂，我遇到很多引導我、啟發我的恩師。他們不只教我演奏，也讓我明白如何成長為更完整的人。透過教學，我能把自己學到的知識分享給不同地方的學生，也看到音樂成為他們自信、快樂和友誼的一部分。",
      "For more than 24 years, I have seen how music can change a student's life. It can help a child express emotions, build discipline, make new friends, and discover a stronger sense of self.": "二十四年來，我親眼看見音樂可以怎樣改變學生的人生。它可以幫助孩子表達情感、建立紀律、認識朋友，並找到更強的自我。",
      "This is one of the reasons I founded Music Fun 100.": "這正是我創立 Music Fun 100 的原因之一。",
      "For Teachers": "給老師",
      "For Students": "給學生",
      "For Parents": "給家長",
      "Contact Waice": "聯絡 Waice",
      "For investment partnership, Music Fun 100 collaboration, teacher opportunities, or student and parent inquiries.": "歡迎就投資合作、Music Fun 100 合作、老師加入、學生及家長查詢聯絡 Waice。",
      "Name": "姓名",
      "Email": "電郵",
      "Topic": "主題",
      "Message": "訊息",
      "Send Inquiry": "送出查詢",
      "Investor Overview": "投資人簡介",
      "Image Slot": "相片位置",
      "Replace with approved photography, caption and source note.": "可替換為已確認可公開的相片、說明及來源備註。",
    },
    zhHans: {
      "Home": "首页",
      "About": "关于",
      "Music & Education": "音乐与教育",
      "Student Success": "学生成就",
      "Leadership & Entrepreneurship": "领导与创业",
      "Media & Press": "媒体与采访",
      "Founder / Music Fun 100": "创办人 / Music Fun 100",
      "Contact": "联系",
      "Founder Portfolio": "创办人作品集",
      "Musician · Educator · Entrepreneur · Founder of Music Fun 100": "音乐人 · 教育者 · 创业者 · Music Fun 100 创办人",
      "Visit Music Fun 100": "前往 Music Fun 100",
      "Join as a Teacher": "老师加入",
      "Find a Music Teacher": "寻找音乐老师",
      "Founder of Music Fun 100": "Music Fun 100 创办人",
      "Musician · Educator · Entrepreneur": "音乐人 · 教育者 · 创业者",
      "With 24 years of music education experience, a cross-cultural teaching background and an entrepreneurial perspective, Waice Che founded Music Fun 100 to make trusted, international music education more accessible to teachers, students and parents.": "Waice Che 拥有 24 年音乐教育经验、跨文化教学背景及创业视野。她创立 Music Fun 100，希望让值得信任、具国际视野的音乐教育，更容易连接老师、学生与家长。",
      "Every teacher deserves to be seen. Every student deserves a wider world through music.": "每一位老师都值得被看见，每一位学生都值得通过音乐看见更大的世界。",
      "Founder Introduction Video": "创办人介绍视频",
      "Replace this placeholder with Waice's YouTube founder introduction video thumbnail.": "之后可替换成 Waice 的 YouTube 创办人介绍视频封面。",
      "A personal introduction from Waice about music education, online teaching, business experience and the vision behind Music Fun 100.": "Waice 亲自介绍她的音乐教育、线上教学、商业背景，以及 Music Fun 100 背后的愿景。",
      "24 Years": "24 年",
      "Music education experience": "音乐教育经验",
      "Global Students": "全球学生",
      "Online teaching across regions": "跨地区线上教学",
      "Students from Canada, United States, Australia, New Zealand, Thailand, Singapore, Italy, UK, Japan, China, Hong Kong, Macau, and more.": "学生来自加拿大、美国、澳大利亚、新西兰、泰国、新加坡、意大利、英国、日本、中国、香港、澳门等地",
      "Founder Vision": "创办人愿景",
      "Making music education more accessible": "让音乐教育更容易接触",
      "A New Path for Music Education": "音乐教育的新方向",
      "Waice believes online education can succeed when it is built with trust, strong communication and meaningful teaching. Through Music Fun 100, she hopes to help teachers find more active student opportunities and help students receive wider international knowledge.": "Waice 相信，只要建立在信任、良好沟通和有意义的教学之上，线上音乐教育是可以成功的。通过 Music Fun 100，她希望帮助老师更主动找到学生资源，也让学生接触更广阔的国际音乐知识。",
      "A Founder Story Built From Experience": "由真实经验累积而成的创办人故事",
      "Flute and harp music training with accurate institutional wording.": "以准确、不夸大的方式呈现长笛与竖琴音乐训练。",
      "Personal youth music competition achievements from Macau.": "Waice 在澳门青年音乐比赛中的个人成就。",
      "Students from different regions achieving strong results through online learning.": "不同地区学生在线上学习中取得良好成绩。",
      "Business, public image and international exchange experience.": "商业、公众形象及国际交流经验。",
      "About Waice": "关于 Waice",
      "Waice Che is a Macau-born musician, educator and entrepreneur whose work connects music training, teaching, public leadership and international perspective.": "Waice Che 是来自澳门的音乐人、教育者与创业者，她的工作连接音乐训练、教学、公众领导力与国际视野。",
      "From Music Training to Teaching": "从音乐训练到教学",
      "What Music Has Given Me": "音乐带给我的意义",
      "Founder Journey": "创办人旅程",
      "Flute and Harp Education by Macau Music Conservatory": "澳门音乐学院长笛与竖琴教育",
      "Flute & Harp Studies": "长笛与竖琴学习",
      "Personal Macau Youth Music Achievements": "澳门青年音乐个人成就",
      "24 Years in Music Education": "24 年音乐教育",
      "Teaching Philosophy": "教学理念",
      "Music Promotion & Adjudication": "音乐推广与比赛评审",
      "Music Performance Photos": "音乐演出照片",
      "Selected performance and master class moments from Waice's music journey.": "Waice 音乐旅程中的演出与大师班精选时刻。",
      "Concert of the Night of Mozart at Macau Cultural Centre": "澳门文化中心《莫扎特之夜》音乐会",
      "Master Class of Paul Edmund-Davies": "Paul Edmund-Davies 大师班",
      "Master Class of Trevor Wye": "Trevor Wye 大师班",
      "Waice previously served as Vice President of the Macau Youth Music Promotion Association and as an adjudicator for selected Macau music competitions. Exact official names and event details can be refined when source material is supplied.": "Waice 曾担任澳门青年音乐推广协会副会长，并曾为部分澳门音乐比赛担任评委。正式英文名称及活动资料可在来源提供后再精准修订。",
      "Student achievements are presented separately from Waice's personal awards, keeping the portfolio clear, credible and respectful.": "学生成就会与 Waice 的个人奖项分开呈现，让网站更清晰、可信，也更尊重学生。",
      "Leadership & Entrepreneurship": "领导与创业",
      "This page presents Waice's business, public image and civic leadership experience as supporting evidence for her founder journey.": "此页展示 Waice 的商业、公众形象及社会领导经验，作为她创办人故事的支持证据。",
      "Public Image & Modeling": "公众形象与模特经历",
      "Entrepreneurial Experience": "创业经验",
      "Civic & International Exchange": "社会事务与国际交流",
      "Former Vice President, Macau Youth Music Promotion Association": "澳门青年音乐推广协会前副会长",
      "Media & Press": "媒体与采访",
      "A curated source-led page for interviews, press features, guest lectures and public appearances.": "精选访问、媒体报道、客席讲座及公开活动记录。",
      "Music Fun 100 was created from Waice's belief that music has no borders, and that music education should not be limited by geography.": "Music Fun 100 源自 Waice 的信念：音乐没有边界，音乐教育也不应受地域限制。",
      "Dear teachers, students and parents,": "亲爱的老师、学生和家长：",
      "Music has shaped my life in many meaningful ways.": "音乐以很多重要的方式塑造了我的人生。",
      "Through music, I met teachers who guided me, inspired me and helped me understand not only how to perform, but how to grow as a person. Through teaching, I have been able to share what I learned with students from different places, and to see music become part of their confidence, happiness and friendships.": "通过音乐，我遇到很多引导我、启发我的恩师。他们不只教我演奏，也让我明白如何成长为更完整的人。通过教学，我能把自己学到的知识分享给不同地方的学生，也看到音乐成为他们自信、快乐和友谊的一部分。",
      "For more than 24 years, I have seen how music can change a student's life. It can help a child express emotions, build discipline, make new friends, and discover a stronger sense of self.": "二十四年来，我亲眼看见音乐可以怎样改变学生的人生。它可以帮助孩子表达情感、建立纪律、认识朋友，并找到更强的自我。",
      "This is one of the reasons I founded Music Fun 100.": "这正是我创立 Music Fun 100 的原因之一。",
      "For Teachers": "给老师",
      "For Students": "给学生",
      "For Parents": "给家长",
      "Contact Waice": "联系 Waice",
      "For investment partnership, Music Fun 100 collaboration, teacher opportunities, or student and parent inquiries.": "欢迎就投资合作、Music Fun 100 合作、老师加入、学生及家长查询联系 Waice。",
      "Name": "姓名",
      "Email": "邮箱",
      "Topic": "主题",
      "Message": "信息",
      "Send Inquiry": "发送查询",
      "Investor Overview": "投资人简介",
      "Image Slot": "图片位置",
      "Replace with approved photography, caption and source note.": "可替换为已确认可公开的照片、说明及来源备注。",
    },
  },
};
